[DriverInfo]
OS=16
Driver=FF Multi-model Print Driver 2
PrinterName=HQ_Cloud Print
OutPort=IP_10.93.22.165
PortMonitor=Standard TCP/IP Port
Comment=
DefaultPrinter=1
Silent=1
[TCP/IP]
HostName=10.93.22.165
Queue=lp
Double Spool=0
SNMP Enabled=0
[FileInfo]
NONDEV=4384
DEVMODE_USER=1592
NONDEV_USER=4384
PRINTERDATA=5784
FONT=5398
FAVORITE=52
TMBINFO=20
TMBINFOUSER=20
CUSTOMSIZE=640
SPECIALPAGE=20
SPECIALPAGEUSER=20
[Favorite01]
FAVORITE=38
DEVMODE=5952
[Favorite02]
FAVORITE=92
DEVMODE=5952
